### ISSUE TITLE
Backport noarch build into a 0.11 branch.

### ISSUE THREAD

**Issue by sodre** [conda-forge/flask-feedstock#16]
I am following up on @jakirkham [request](https://github.com/conda-forge/airflow-feedstock/pull/6#issuecomment-389428335)  in conda-forge/airflow-feedstock#6 to investigate why it did not build against Python 3.6. 

It turned out that the dependency that did not resolve in Python 3.6 was `flask >=0.11,<0.12`. Would you be able to backport the 1.x series into a 0.11 branch?

I did not initiate the PR because it would go against the master branch. If you know how to prevent that let me know :)

---
The commit below does what I am asking, and it increases the build number of 0.11 from 0 to 1.

**Comment by jakirkham** [comment]
Multibranch feedstocks can be used to support legacy versions and/or multiple active versions. Maybe that would work for your use case?

**Comment by sodre** [comment]
Yes, that is sufficient, but I thought that the maintainers needed to created the separate branch before I can issue a PR, is that correct?

**Comment by jakirkham** [comment]
So it looked like getting this going would be a bit challenging given how old that release is. Went ahead and did this to free up the maintainers from figuring that out. Have added a legacy `v0.11.1` branch stemming from the `0.11.1` release and have PR ( https://github.com/conda-forge/flask-feedstock/pull/17 ) up to refresh it and get it using `noarch: python`. Please take a look.

**Comment by marcelotrevisani** [comment]
Should we close this issue?
@jakirkham @sodre

**Comment by jakirkham** [comment]
Yep, looks solved in PR ( https://github.com/conda-forge/flask-feedstock/pull/17 ). Thanks for the reminder. 🙂
