### ISSUE TITLE
Update to 0.12

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/flask-feedstock#3]
Flask 0.12 was released on Dec. 21, 2016 and is available via the conda default channel, so this recipe should probably be updated to keep up.

**Comment by goanpeca** [comment]
@jakirkham what is the current mechanism to know that a new package has been updated. I wrote a small webserver for my own use that queries pypi/conda-forge and sends me an email when one of the packages I make recipes for has a new release.

Thoughts on this?

**Comment by synapticarbors** [comment]
I tend to run `feedstockrot` (https://github.com/conda-forge/feedstockrot-feedstock) to find out-of-date recipes.

**Comment by ocefpaf** [comment]
>  I wrote a small webserver for my own use that queries pypi/conda-forge and sends me an email when one of the packages I make recipes for has a new release.

OpenSUSE has a similar thing and they e-mail the all maintainers. Maybe we should start making that official but I believe some maintainers will want an option to drop out of that automatic e-mail.

**Comment by goanpeca** [comment]
>Maybe we should start making that official but I believe some maintainers will want an option to drop out of that automatic e-mail.

We could simply open a new issue on the repo and tag developers listed in the maintainers section of the recipe.

**Comment by ocefpaf** [comment]
> We could simply open a new issue on the repo and tag developers listed in the maintainers section of the recipe.

That is a much better idea!

**Comment by goanpeca** [comment]
Ok I will add some extra logic when I find some time and make the repo public and we can iterate on it

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/conda-forge.github.io/issues/51

**Comment by jakirkham** [comment]
This appears to be fixed.

<img width="1552" alt="screen shot 2017-03-23 at 20 04 56" src="https://cloud.githubusercontent.com/assets/3019665/24275183/03a972de-1004-11e7-9d96-3457855a4cde.png">
