### ISSUE TITLE
Create branch for flask 1.x

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/flask-feedstock#37]
I'm working in an environment where some dependencies haven't yet moved on to flask 2. However, conda-forge hasn't packaged flask 1.1.4, the last release in the 1.x line. It would help out quite a bit to have this packaged for conda-forge.

I'd be happy to package the release, but I'd need a maintainer to create a branch at 7af7181ed7efe3f2a9c139778d671703f24c9240 for me - or become a maintainer on this feedstock and do it myself. I'm fine with either, please let me know what you think and how you'd like to proceed @conda-forge/flask.

**Comment by xylar** [comment]
I have already done this in https://github.com/conda-forge/flask-feedstock/pull/31.  Can you provide more info so we can understand why you're not able to install this version?

**Comment by h-vetinari** [comment]
Apologies for the noise, I should have checked this better. I guess 1.1.4 didn't show up for me due to some constraint after the upper bounds were added in https://github.com/conda-forge/flask-feedstock/commit/79c72c5e7b8220c2cf60395dffd8402d3855ae99.

**Comment by h-vetinari** [comment]
I traced the resolution errors down to https://github.com/conda-forge/jinja2-feedstock/pull/32
