### ISSUE TITLE
Missing OSX build

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/flask-feedstock#6]
For some reason, the new `0.12` version didn't produce a build for `osx` on [anaconda](https://anaconda.org/conda-forge/flask/files). When I try re-running [the Travis CI build](https://travis-ci.org/conda-forge/flask-feedstock), hoping that that will kick the new version up successfully, it errors out because it can no longer find the pull request.

That said, it looks like @lexual has a [pull request](https://github.com/conda-forge/flask-feedstock/pull/5) out for a rebuild with `conda-smithy 2.1.1`, which might fix the problem when it gets merged.

**Comment by jakirkham** [comment]
This appears to be fixed.

<img width="1552" alt="screen shot 2017-03-23 at 20 02 40" src="https://cloud.githubusercontent.com/assets/3019665/24275140/b1f1829c-1003-11e7-8867-a34611fc44c1.png">
